pipeline {
    agent any
    stages {
        stage('Git Webhook Checkout') {
            steps {
                 sh 'echo "Git checkout passed"'
            }
        }
        stage('Compile') {  
            steps {
                sh 'cd devops/ && mvn compile'
            }
        }
        stage('Test') {
            steps {
                sh 'cd devops/ && mvn test'
            }
        }
        stage('Build') {
            steps {
                sh 'cd devops/ && mvn clean install'
            }
        }
        stage('Static Code Analysis') {
            steps {
                withSonarQubeEnv('sonarqubeserver') {
                    sh 'cd devops/ && mvn sonar:sonar'
                }
            }
        }
        stage('Build and Push Docker Image') {
            steps {
                script {
                    def dockerImage = "jeeva1235/cicd:${env.BUILD_NUMBER}"
                    sh "cd devops/ && docker build -t ${dockerImage} ."
                    docker.withRegistry('https://index.docker.io/v1/', 'dcoker_cred') {  // Corrected docker credential ID
                        docker.image(dockerImage).push()
                    }
                }
            }
        }
        stage('Update GitHub Repository with Manifest') {
            environment {
                GIT_CREDENTIALS_ID = 'git-cred'
                GIT_REPO_URL = 'https://github.com/Jeevagithubvj/Jeeva.git'
                GIT_BRANCH = 'main'
            }
            steps {
                script {
                    sh '''
                        rm -rf Jeeva
                        git clone ${GIT_REPO_URL}
                        cd Jeeva/k8
                        git checkout ${GIT_BRANCH}
                    '''

                    sh '''
                        sed -i 's|image:jeeva1235/cicd:.*|image:jeeva1235/cicd:${env.BUILD_NUMBER}|g' Jeeva/k8/manifest.yaml
                    '''

                    sh '''
                        git config --global user.email "jeeva.v.devops@gmail.com"
                        git config --global user.name "vijay"
                        git add Jeeva/k8/manifest.yaml
                        git commit -m "Update manifest with Docker image tag ${BUILD_NUMBER}
                        git push origin ${GIT_BRANCH} -f
                    '''
                }
            }
        }
    }
}
