pipeline{
 agent any
   stages{
     stage('git checkout')
     {
       steps{
         sh 'echo passed'
       }
     }
     stage('complile')
           {
            steps{
              sh 'cd devops/ && mvn compile'
            }
           }
     stage ('test')
    {
     steps{
      sh 'cd devops/ && mvn test'
     }
    }
    stage('build')
    {
     steps{
      sh 'cd devops/ && mvn clean install'
     }
    }
     stage('sonareqube')
    {
     steps{
      withSonarQubeEnv(credentialsId: 's') {
         }
     }
    }
    
   }
  
}
