pipeline {
    agent any
    stages {
        stage('Git webhook Checkout') {
            steps {
                 sh 'echo "Git checkout passed"'
            }
        }
        stage('Compile') {
            steps {
                sh 'cd devops/ && mvn compile'
            }
        }
        stage('Test') {
            steps {
                sh 'cd devops/ && mvn test'
            }
        }
        stage('Build') {
            steps {
                sh 'cd devops/ && mvn clean install'
            }
        }
        stage('Static Code Analysis') {
            steps {
                withSonarQubeEnv('sonarqubeserver') {
                    sh 'cd devops/ && mvn sonar:sonar'
                }
            }
        }
        stage('Build and Push Docker Image') {
            steps {
                script {
                    def dockerImage = "jeeva1235/cicd:${env.BUILD_NUMBER}"
                    sh "cd devops/ && docker build -t ${dockerImage} "
                    docker.withRegistry('https://index.docker.io/v1/', 'dcoker_cred') {
                        docker.image(dockerImage).push()
                    }
                }
            }
        }
    }
}
